.travis.yml
package.json

Modifying travis.yml file to cache node modules

Modifying travis.yml file to cache node modules

---

.eslintrc.js
.travis.yml
config/dev-env.js
config/prod-env.js
config/test-env.js
package-lock.json
package.json
src/api/ApiService.js
src/api/HealthCheckService.js
src/api/ImageService.js
src/api/SocialService.js

Adding API service
- Added  `src/api/*` files to add API layer.
- Modified `.eslintrc.js` to fix issue with file name.
- Modified `config/*-env.js`files  to add api url.
- Configure JsDoc and add more documentation.

Adding API service

---

src/api/ApiService.js
src/api/HealthCheckService.js
src/api/ImageService.js
src/api/SocialService.js
src/main.js

Fixes for eslint errors
- Modified files to fix errors discovered by running linter.
1. Run `npm lint` and notice that there are no errors.
-
-

Fixes for eslint errors

---

index.html
src/api/ImageService.js
src/api/LinkService.js
src/api/ListService.js
src/assets/filter-icon.svg
src/assets/remove-icon.svg
src/assets/search-icon.svg
src/components/FooterSection.vue
src/components/HeaderSection.vue
src/components/HeroSection.vue
src/components/NavSection.vue
src/components/SearchFilter.vue
src/components/SearchForm.vue
src/components/SearchGrid.vue
src/components/ShareBar.vue
src/pages/BrowsePage.vue
src/pages/Homepage.vue
src/pages/PhotoDetailPage.vue
src/pages/ShareListPage.vue
src/router/index.js
src/store/action-types.js
src/store/index.js
src/store/list-store.js
src/store/mutation-types.js
src/store/search-store.js

Adding share bar and code cleanup
-
-

Adding share bar and code cleanup

---

src/components/NavSection.vue
src/components/SearchGrid.vue
src/components/SearchGridCell.vue
src/pages/PhotoDetailPage.vue

Enhancing image loading on search grid page
-
-
-
1.
-
-

Enhancing image loading on search grid page

---

src/api/ApiService.js

Switching API to HTTPS
-
-
-
1.
-
-

Switching API to HTTPS

---

src/components/FooterSection.vue
src/components/SearchGridFilter.vue
src/components/SearchGridForm.vue
src/main.js
src/pages/BrowsePage.vue

Fixes for linter

---

src/components/HeaderSection.vue
src/components/SearchGridForm.vue
src/pages/BrowsePage.vue
src/pages/PhotoDetailPage.vue

Adding fixed header when scrolling on browse page
-
-
-
1.
-
-

Adding fixed header when scrolling on browse page

---

src/api/ShareListService.js
src/components/ShareBar.vue

Modifying image list data service
-
-
-
1.
-
-

Modifying image list data service

---

src/api/ShareListService.js
src/store/share-list-store.js

Fix for linter and list image param
1.
-
-

Fix for linter and list image param

---

src/api/ShareListService.js
src/components/SearchGrid.vue
src/components/ShareList.vue
src/store/share-list-store.js

Fix for editing list when multiple items selected

Fix for editing list when multiple items selected

---

src/api/ShareListService.js
src/components/ShareList.vue
src/components/SocialShareButtons.vue
src/pages/BrowsePage.vue
src/pages/ShareListPage.vue
src/store/mutation-types.js
src/store/share-list-store.js

Modifications to Share list notification and social button
-
-
-
1.
-
-

Modifications to Share list notification and social buttons

---

src/components/SearchGridFilter.vue

Fixes for filter values and display text

Fixes for filter values and display text

---

src/components/ShareList.vue

Fix for share list dialogue
Closes issue #65

Fix for share list dialogue

---

index.html
src/App.vue
src/components/SearchGrid.vue
src/components/SearchGridFilter.vue
src/components/SearchGridForm.vue
src/components/ShareList.vue
src/pages/BrowsePage.vue
src/pages/PhotoDetailPage.vue
src/pages/ShareListsPage.vue
src/store/mutation-types.js
src/store/search-store.js
src/store/share-list-store.js

Fixes for peer ui review
- Adds public lists notification to share lists page
- Fixes issues with filter not staying applied, when search is updated.
- Closes filter when scrolling
- Adds notification when adding list for share list dialogue.

Fixes for peer ui review

---

src/pages/ShareListPage.vue

Fix for displaying image thumbnail on pinterest

Fix for displaying image thumbnail on pinterest

---

src/components/SearchGrid.vue

Fixes issue with search grid key when iterating.

Fix for search grid key

---

src/pages/PhotoDetailPage.vue

Adding image dimensions on image detail page

Adding image dimensions on image detail page

---

package-lock.json
package.json
test/unit/jest-conf.js
test/unit/specs/components/search-form.spec.js

This PR fixes the tests so that the build turns back green ✅

Fix unit tests

---

.eslintrc.js
index.html
src/router/index.js

Fixed issues raised in code review for #127.
- Fixed indentation by replacing tabs with spaces.
- Added a comment to clarify why eslint is disabled for a portion of the code.

Fixed indentation and added a comment.

---

src/components/SearchGrid.vue
src/pages/PhotoDetailPage.vue

- added alt attribute to image results and provider icons in the SearchGrid component.
- added alt attribute to image on the PhotoDetailPage.
closes #131

add alt tags to image search and show page

---

src/components/LicenseIcons.vue
src/components/SearchGrid.vue
src/components/SearchGridCell.vue

Fixes the opening the image details on a new tab with the Command key (Mac) and Ctrl key (Windows/Linux).

Fix image link open new tab 

---

src/components/LicenseIcons.vue
src/components/PhotoDetails.vue
src/components/PhotoTags.vue
src/components/RelatedImages.vue
src/pages/PhotoDetailPage.vue
src/styles/photodetails.scss

Fixes #136 (Bug description in the issue)
This also refactors some components that were in the `PhotoDetailsPage.vue` out into their own components.
Removes the Viewer component, which wasn't being used.

Fix back to search results navigation

---

src/components/PhotoDetails.vue

Shows "Not Available" when image creator is null

---

src/assets/plus-icon-black.svg
src/components/PhotoDetails.vue
src/components/ShareList.vue
src/pages/BrowsePage.vue
src/pages/PhotoDetailPage.vue
src/styles/photodetails.scss

Fixes #117 
_see it in action_

Lets users add image to list in Photo details page

---

Dockerfile
config/index.js
docker-compose.yml

Part of #173 
This enables developers to setup and have the frontend up and running with just one command:
`docker-compose up`

Docker support for local development

---

.github/pull_request_template.md

Simplifies the PR template removing unnecessary requirements, keeping only the minimum that should be required at first glance.
Part of #175

Simplify Pull Request template

---

.eslintrc.js
src/api/ImageService.js
src/components/LicenseIcons.vue
src/components/PhotoDetails.vue
src/components/SearchGrid.vue
src/components/SearchGridFilter.vue
src/components/ShareList.vue
src/pages/BrowsePage.vue
src/pages/PhotoDetailPage.vue
src/store/search-store.js
src/utils/prepareSearchQueryParams.js
test/unit/sampleStore/index.js
test/unit/specs/components/footer-section.spec.js
test/unit/specs/components/nav-section.spec.js
test/unit/specs/components/photo-details.spec.js
test/unit/specs/components/search-form.spec.js
test/unit/specs/components/search-grid-cell.spec.js
test/unit/specs/components/search-grid.spec.js
test/unit/specs/pages/homepage.spec.js
test/unit/specs/store/search-store.spec.js
test/unit/specs/utils/prepareSearchQueryParams.spec.js
test/unit/test-utils/render.js

Creates a search filter for creator and tags
Fixes #166

Enables search filter by creator/tags

---

src/pages/ShareListsPage.vue

Add Google Form link on lists page

---

index.html

[Added metatags for improving social integration in the file index.html
[Link to existing Issue #165 ]

Added metatags for social integration

---

.cc_metadata.yml

Adding CC metadata file to feature this project on the CC Open Source website: (see https://github.com/creativecommons/creativecommons.github.io-source/pull/30)

Added CC metadata file.

---

.cc_metadata.yml

Renamed file, fixed typo in name.

---

build/webpack-base-conf.js
build/webpack-dev-conf.js
build/webpack-prod-conf.js
config/.env
config/dev-env.js
config/prod-env.js
config/test-env.js
package-lock.json
package.json
src/components/PhotoDetails.vue
src/featureFlags/index.js

Exposes feature flags read from env variables
Fixes #215

Feature flags

---

test/unit/specs/components/license-icons.copy.js
test/unit/specs/pages/homepage.spec.js

Added tests for LicenseIcons and HomePage
Relates to issue #232

Add LicenseIcons and HomePage tests

---

config/.env
src/components/PhotoDetails.vue
src/components/SocialShareButtons.vue
src/featureFlags/index.js
src/pages/PhotoDetailPage.vue
test/unit/specs/components/photo-details.spec.js

Uses feature flag to enable/disable the social sharing buttons on the photo details page
Fixes #266

Feature flag for social sharing buttons

---

src/components/PhotoDetails.vue
test/unit/specs/components/photo-details.spec.js

I added the changes proposed by Jane, which aim to solve the following two issues.
- Make user aware of CC Search as a product
- Include reference to relevant CC social media account
[Link to existing Issue #]
https://github.com/creativecommons/cccatalog-frontend/issues/271

Fixed issue #271, to make user aware of CC-Search as a product

---

index.html

Fixes #236 
Applied "overflow-x: auto" to table's parent div which solves the issue.

About table overflow

---

.github/pull_request_template.md
CODEBASE.md
CODEOWNERS
CODE_OF_CONDUCT.md
CONTRIBUTING.md

Improvements to our contribution guidelines documentation
Fixes #175

Contribution guidelines

---

index.html

This PR address #291 raised by @janeatcc.
It was just a matter of updating the `<meta name="description" ...>` tag in the `index.html` file.
<details>
<summary>
</summary>
<p>
(b) The contribution is based upon previous work that, to the best of my knowledge, is …

Update the description meta tag

---

index.html

@janeatcc wanted the description meta tag to be updated to remove the "and confidence" part
[Link to existing Issue #]
Fixes #291 
---
(b) The contribution is based upon previous work that, to …

Updates the description meta tag

---

index.html
src/App.vue
src/components/HeaderSection.vue
src/components/HeroSection.vue
src/components/NavSection.vue
src/pages/BrowsePage.vue
src/pages/HomePage.vue
test/unit/specs/pages/homepage.spec.js

Removes the top categories from Home page
Fixes #285 
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with …

Remove top categories from home page

---

src/components/HeroSection.vue

Add link to the old cc search portal

---

index.html

Fixes the title and description social metatags
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, …

Update social description meta tags

---

index.html

Fixes the GA account code for the new domain used in production
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with …

Fixes the GA account code for production

---

src/components/FooterSection.vue

Fixes #372 and more!
This PR:
- Use `foundation` responsive classes the right way
- Delete unnecessary/incorrect responsive classes
- Fix the footer `logo` on multiple screen resolutions (i.e. Stretched Logo)
- Stretch the footer' sections
Here's the old vs new UI:
Before:
After:
Before:
After:
---
(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source …

Fix the 'footer' responsive issues / Better use of 'foundation' classes

---

src/components/PhotoDetails.vue
src/store/search-store.js
src/utils/decodeImageData.js
src/utils/prepareSearchQueryParams.js
test/unit/specs/store/search-store.spec.js
test/unit/specs/utils/decodeImageData.spec.js

Fixes #374 #365 
Decodes image string data directly on store for search results and photo details
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under …

Fix encoding of image data

---

src/components/HeaderSection.vue
src/components/HeroSection.vue
src/components/NavSection.vue
src/components/SearchGridForm.vue
src/pages/CollectionBrowsePage.vue
src/pages/PhotoDetailPage.vue

Fixes the search box placeholders text
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether …

Search box placeholders

---

src/components/ImageInfo.vue
src/components/MasonrySearchGridCell.vue
src/styles/photodetails.scss
src/utils/getProviderLogo.js

Adds provider logo to image info page

---

src/pages/AboutPage.vue

Update about page text and links

---

src/pages/BrowsePage.vue

Remove redundant search term on results page

---

src/api/ImageService.js
src/pages/PhotoDetailPage.vue
src/store/search-store.js
test/unit/specs/store/search-store.spec.js

Use related images API

---

src/components/FooterSection.vue
src/pages/SearchHelpPage.vue

Fix syntax guide typo and position

---

src/components/PhotoDetails.vue
test/unit/specs/components/photo-details.spec.js

Fix CC0 license display

---

src/components/NavSection.vue

Fix navbar search box spacing issue

---

config/.env
package-lock.json
package.json
src/clientEntry.js
src/sentry/browser.js
src/sentry/initSentry.js
src/sentry/server.js
src/serverEntry.js
test/unit/specs/sentry/init-sentry.spec.js

Adds Sentry config

---

src/utils/decodeData.js
test/unit/specs/utils/decodeData.spec.js

Fix decode data exception

---

package-lock.json
package.json
server.js
src/App.vue
src/pages/AboutPage.vue
src/pages/CollectionsPage.vue
src/pages/SearchHelpPage.vue
src/pages/mixins/ServerPrefetchProvidersMixin.js
src/pages/server/BrowsePage.vue

SSR optimizations

---

package-lock.json
package.json
src/clientEntry.js
src/components/ScrollButton.vue
src/components/SearchGrid.vue

Fixes #169 
This implements the scroll button for the infinite scrolling.
---
(b) The contribution …

Scroll to top button

---

package-lock.json
package.json
src/components/SearchGridFilter.vue

Fix search by creator on clear filters

---

src/components/SearchGridFilter.vue
src/pages/AboutPage.vue

Change provider to source

---

index-server.html

Fixes #270 
Fixes some social meta tags
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether …

Fix social meta tags

---

src/components/ImageAttribution.vue

Remove quotes from untitle image title

---

src/components/FooterSection.vue
src/components/HeroSection.vue
src/components/LicenseIcons.vue
src/components/NavSection.vue
src/components/SearchGridFormNewFilter.vue

Fixes #XX
---
(b) The contribution is based upon previous work that, to the best of my knowledge, …

Adds alt text for images and logos

---

index-server.html
index.html
src/components/HeroSection.vue
static/opensearch.xml

Fixes #254 
Adds an open search specification and also updates index.html and search input for Open Search autodiscovery

add open search specification #254

---

src/components/SearchGridFormOriginal.vue

Fixes #532
Tested on Android with Chrome browser.
---
<details>
<summary>Developer Certificate of Origin Version 1.1</summary>
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit …

Dismiss keyboard after search form submit on mobile

---

src/components/HeroSection.vue
src/components/HomeLicenseFilter.vue
src/main.js
src/utils/getParameterByName.js
test/unit/specs/utils/getParameterByName.spec.js

Home page search form submit without JS

---

src/components/SearchGridForm.vue

Adds code from #535 that got lost in some code merge.
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with …

Dismisses mobile keyboard after search submit

---

package-lock.json
src/components/FilterChecklist.vue

This is a fix to the issue of filter sidebar drop-down arrow not looking like a link. (i.e the cursor not displaying as a pointer when hovered on)
I was able to fix this issue by adding a `cursor: pointer;` style rule to the .`filter-dropdown-visibility-button` class found in  `./src/components/FilterChecklist.vue` file which was the class responsible for the behavior of the drop-down arrows.
---
(a) The …

Fixed filter sidebar arrow issue #547

---

config/.env
index-server.html
index.html
package-lock.json
package.json
src/App.vue
src/components/FooterSection.vue
src/components/HeroSection.vue
src/components/HomeLicenseFilter.vue
src/components/NavSection.vue
src/styles/text-only-page.scss

Integrate https://github.com/creativecommons/vocabulary into CC Search.
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that …

Homepage redesign

---

README.md

I have deleted the link because on going to that link leads to 404 page.
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work …

Updating Link

---

src/components/NavSection.vue

**Work Done:**
Updated Navbar 
**Before:**
**After:**
**As firstly the feedback was getting out of the navbar while resizing now corrected by changing @media (min-width: 55em)** 
(b) The contribution is based upon previous work that, to the best of my knowledge, is …

Updated Navbar

---

src/components/NavSection.vue

**Work done:**
made the search bar respond properly
**before:**
**After:**
**As search bar was getting out of the navbar while resizing now corrected.**
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate …

changed in navbar

---

build/webpack-prod-conf.js
index-server.html
index.html

Fixes #553 
Added local path to opensearch.xml static/opensearch.xml to `index.html` and `index-server.html`

Added the opensearch.xml link

---

src/pages/SearchHelpPage.vue

**A spelling mistake in the search help page**
**Before:**
**After:**
**Spelling error in the search help page corrected by changing "source to license"**
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an …

Changing spelling

---

src/components/FilterChecklist.vue

Fixes #591
Previously for every iteration of v-for the v-if condition is to be evaluated which may create performance issues, later on, this `PR` solves this issue with just one v-if check before running the loop
---
(b) The contribution is based upon previous work …

Added template tag above the v-for node

---

src/components/SearchGridFilter.vue
src/pages/client/BrowsePage.vue

Fix sidebar background color

---

package-lock.json
package.json
src/api/ApiService.js
src/api/UsageDataService.js
src/main.js

Refactor api service

---

index-server.html
index.html
package-lock.json
package.json
src/App.vue
src/components/CopyButton.vue
src/components/HeroSection.vue
src/components/ImageAttribution.vue
src/components/NavSection.vue
src/components/SearchGridFilter.vue
src/components/SearchGridManualLoad.vue
src/components/Watermark.vue
src/styles/app.scss
src/styles/global.scss
src/styles/main.scss
test/unit/specs/components/watermark.spec.js

Integrate Vocabulary into CC Search

---

build/utils.js
src/App.vue

Something broke with the import of removed .scss files. This PR fixes that

Fix dev build

---

src/abTests/createSixpackSession.js
test/unit/specs/abTests/ab-tests.spec.js

Fix sixpack url

---

src/components/ImageInfo.vue

Reimplements the changes in #621 which got weirdly merged and the code isn't in `develop`
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that …

fix image info source logo image

---

CONTRIBUTING.md

Explicitly document that all PRs must target develop

---

src/pages/SearchHelpPage.vue
src/store/filter-store.js
src/utils/getProviderName.js
test/unit/specs/store/filter-store.spec.js

Fix source filter

---

src/components/CollectionItem.vue
src/components/FooterSection.vue
src/components/HeaderSection.vue
src/components/HeroSection.vue
src/components/PhotoTags.vue
src/components/SearchGridForm.vue
src/components/SocialShareButtons.vue
src/components/Watermark.vue
src/main.js
src/pages/AboutPage.vue
src/pages/CollectionsPage.vue
src/pages/HomePage.vue
src/pages/client/BrowsePage.vue
src/pages/client/CollectionBrowsePage.vue
src/pages/client/PhotoDetailPage.vue
src/pages/server/BrowsePage.vue
src/pages/server/CollectionBrowsePage.vue
src/pages/server/PhotoDetailPage.vue

Replace Foundation Grids with Vocabulary/Bulma's 

---

src/components/HeroSection.vue

Fixes #705 
Autofocus is an issue for accessibility so its adviable to remove it till some accessibility usability tests are carried out
---
(b) The contribution is based upon previous work …

remove autofocus on homepage

---

src/pages/mixins/PhotoDetailMixin.js

Write some comments about vue-router functions

---

src/components/SearchGridForm.vue
src/styles/results-page.scss

Fixes #777 #776 #774 
Fixes some of the issues with the search form on the results page on mobile screens.
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right …

Improved search results page form on mobile

---

package-lock.json
package.json
src/components/FooterSection.vue
src/components/SearchGridManualLoad.vue

Adds footer from Vocabulary

---

src/components/SearchGridCell.vue

Fixes #800 by @panchovm 
<details>
```
Version 1.1
Suite D4700
of my knowledge, is …
```

Improved image grid design

---

src/App.vue
src/components/SearchGridManualLoad.vue

Fixes https://github.com/creativecommons/vocabulary/issues/242 by @panchovm 
At different places in front-end, some texts have color as `#2c3e50` and some have `#333333`. So this has been made uniform by changing the font color to `#333333` as was instructed in the issue.
The screenshot below shows the updated color in the portions pointed out in the issue.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```

Fix two similar font-colors to a uniform one

---

src/components/ScrollButton.vue

Fixes #835 by Me
<details>
```
Version 1.1
Suite D4700
license and I have the right under that license to submit …
```

Fixes bottom to top scroll button functionality

---

build/webpack-base-conf.js
src/components/FooterSection.vue
src/components/HeroSection.vue
src/components/NavSection.vue
test/unit/specs/components/footer-section.spec.js

Fixes #861 
<details>
```
Version 1.1
Suite D4700 …
```

Use Vocabulary SVGs

---

src/pages/SearchHelpPage.vue

Fixes #767 by @aldenstpage 
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to …
```

updated search guide

---

src/components/ImageAttribution.vue
src/components/LegalDisclaimer.vue
src/components/ReuseSurvey.vue
src/styles/photodetails.scss

Fixes #804 by @panchovm 
<details>
```
Version 1.1
Suite D4700
license and I have the right under that license to …
```

fix margins in image attribution component

---

src/components/FilterDisplay.vue
test/unit/specs/components/filter-display.spec.js

Fixes #885 
<details>
```
Version 1.1
Suite D4700 …
```

Fix filter by caption text

---

src/components/ContentReport/ContentReportForm.vue
src/components/ContentReport/DmcaNotice.vue
src/components/ContentReport/DoneMessage.vue
src/components/ContentReport/ReportError.vue

Fixes #914 
<details>
```
Version 1.1
Suite D4700 …
```

Fix typo report form

---

src/components/ImageDetails/CopyLicense.vue

Fixes #983 by @annatuma
This fixes the git log of #987 
<details>
```
Version 1.1
Suite D4700
license and I have …
```

Updates to "Credit the Creater" Box 

---

CODEOWNERS

<details>
```
Version 1.1
Suite D4700
work with …
```

Updated team name

---

src/components/SearchGridManualLoad.vue

Fixes #1010  by @annatuma 
Removed Search Relevance Question on Collections pages
`In Collections Page`
`Normal Search`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Removed Search Relevance Question on Collections pages

---

index.html
package-lock.json
package.json
src/App.vue
src/pages/client/PhotoDetailPage.vue
src/router/client.js

Fixes #1014  by @annatuma.
Add **[vue-meta](https://vue-meta.nuxtjs.org/)** plugin to manage this specific tag.
The `monetization` tag is placed in `src/App.vue` file to replicate it to all pages and then removed in `src/pages/client/PhotoDetailPage.vue` (Ref.: [Remove parent property by child](https://vue-meta.nuxtjs.org/guide/special.html#remove-parent-property-by-child)).
Maybe PR #1003 should be checked before this, I did not make any changes to server-side files.
- Go to any page other than a single result page and check there is the tag openning developer tools of browser.
- Go to any single result photo page and verify the tag is not present.
index.md`).
<details> …

Add web monetization tag

---

src/api/ImageProviderService.js
src/pages/CollectionsPage.vue

index.md`).
<details>
```
Version 1.1
Suite D4700
of my knowledge, is …
```

Moved Smithsonian & McCord Museum to Museums 

---

src/pages/SearchHelpPage.vue

Fixes #1026  by @AyanChoudhary 
Update the link to "dog|cat" search query in search guide page.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the …
```

fix cat|dog link in search guide

---

index-server.html
index.html

Fixes #1027  by @annatuma 
Update the google analytics code. If ccsearch. or search. as subdomains track to the GA production ID UA-2010376-33 else use UA-2010376-36
index.md`).
<details>
```
Version 1.1
Suite D4700
have …
```

update google analytics

---

src/components/FooterSection.vue
src/components/HeroSection.vue
src/components/HomeLicenseFilter.vue
src/components/LocaleSelector.vue
src/components/NavSection.vue
src/locales/en.json
src/locales/fr.json
test/unit/specs/components/home-license-filter.spec.js
test/unit/specs/components/nav-section.spec.js

Fixes #942 by @brenoferreira 
Internationalizes the CC search homepage
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Internationalize homepage, header and footer

---

src/components/LocaleSelector.vue
src/components/NavSection.vue
src/i18n.js
src/locales/en.json
src/locales/fr.json
src/pages/AboutPage.vue
src/pages/SearchHelpPage.vue

Fixes #942 by @brenoferreira 
Internationalizes about page and search-help page and handles the persistence of locale.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Internationalize About Page and Search Guide Page

---

src/components/CollectionItem.vue
src/locales/en.json
src/locales/fr.json
src/pages/CollectionsPage.vue
src/pages/FeedbackPage.vue
src/pages/NotFoundPage.vue
test/unit/specs/pages/collectionspage.spec.js

Fixes #942 by @brenoferreira 
Internationalizes feedback page, collections page and not found page with appropriate changes in tests.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```

Internationalize feedback page, collections page and not found page

---

src/components/ImageDetails/PhotoDetails.vue

Fixes #961 
I have made certain changes related to margin to match the spaces defined for grid in Mockup S3.

margin changes in PhotoDetails.vue file

---

src/components/Filters/LicenseExplanationTooltip.vue
src/components/LicenseExplanations.vue

Fixes #1047 by @annatuma 
Fixed the license explanation modal according to the design guidelines.
Refactored the code to use unordered list for rendering license explanation points instead of `div` blocks. 
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```

Refactored license explanation modal to follow design guidelines

---

src/components/Filters/LicenseExplanationTooltip.vue
src/components/ImageDetails/CopyLicense.vue
src/components/LicenseExplanations.vue

Fixes #1055 
Fixes some small visual issues outlined in 1055
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```

Fix visual regressions from recent updates

---

CODEOWNERS

<details>
```
Version 1.1
Suite D4700
work with …
```

Adding collaborators to codeowners

---

package-lock.json
package.json

Fixes #1058 by @zackkrida 
Updates vocabulary to the latest version
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```

Update vocabulary to 2020.07.1

---

src/components/HeroSection.vue

Fixes recently implemented autofocusing of the homepage search input.

Add js fallback for autofocus on home page

---

src/components/HeroSection.vue

Fix a broken test from the last pushed autofocus fix. 
<details>
```
Version 1.1
Suite D4700 …
```

Fix autofocus breaking test

---

src/components/FooterSection.vue
src/components/HeroSection.vue
src/pages/HomePage.vue

Fixes #488  by @brenoferreira 
Makes accessibility improvements to CC search website, including but not limited to proper landmark division, improved aria-labels, aria-roles, and better keyboard navigation.
Our accessibility scores for the homepage went from 84 to 91 after the present changes and more improvement is expected after the contrast issues are resolved.
Changes in individual pages:
1. Homepage: 84 -> 91 | +7
Coming up soon
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

Accessibility Improvements

---

src/components/HeroSection.vue
src/components/NavSection.vue
src/pages/AboutPage.vue
src/pages/SearchHelpPage.vue

Partially fixes #488  by @brenoferreira 
Improves accessibility for about page and search-guide page.
The accessibility scores for both the pages improved:
1. About Page: 78 -> 97 | +19
2. Search-Guide Page: 76 -> 97 | +23
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```

Accessibility

---

src/components/ImageDetails/ImageInfo.vue
src/components/ImageDetails/PhotoDetails.vue
src/pages/PhotoDetailPage.vue
test/unit/specs/components/ImageDetails/image-info.spec.js

Fixes #1049 by @annatuma 
Re-style the single result 'info' tab to be more compact and show the provider
The API does not currently provide the image 'type' (file extension, mimetype, or other form) desired by the [design](https://www.figma.com/proto/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=1224%3A27&scaling=min-zoom). I could technically parse the image on each page and read the mime type, but this would be excessive front-end computation and not beneficial to our users.
We should discuss if showing the 'type' is a blocker for this release or if we would rather see the provider field and new appearance go live.
> before
> after
index.md`).
<details> …

Single result page updates (show provider)

---

src/components/Filters/FilterChecklist.vue
src/components/HeroSection.vue
src/i18n.js

Fixes SSR after merging in the i18n branch. There was a check to `window` which is undefined server-side.

Fix development site

---

src/App.vue

Fixes #1030 
Loads the global header from our CDN, so it's always the latest version. Loads deferred so it doesn't interfere with ordinary page load.
Style wise, it doesn't _technically_ break or obscure anything, but seems to make clear that we should use the non-small version of the Design Language site header.
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```

Add CC Global Header

---

package-lock.json
src/components/Filters/FilterChecklist.vue

Fixes #1103  by me
Disabled Licence-Explanation Tooltip
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based …
```

Disabled Licence-Explanation Tooltip when licences are disabled

---

src/components/Filters/LicenseExplanationTooltip.vue
src/components/ImageDetails/ImageAttribution.vue
src/locales/en.json

Fixes #1099 and Fixes #1100  by @annatuma 
This PR removes the 'license' word from PDM and CC0 as described in the issues.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Removed 'license' from PDM and CC0 in reuse tab and filters

---

.github/workflows/sentry-release.yml
config/.env
package-lock.json
package.json
server.js
src/clientEntry.js
src/sentry/browser.js
src/sentry/initSentry.js
src/sentry/server.js
src/serverEntry.js
test/unit/specs/sentry/init-sentry.spec.js

Related to #1042 by @zackkrida 
This PR makes several improvements to our Sentry configuration. **Note: Prequisite infrastructure PR here: https://github.com/creativecommons/ccsearch-infrastructure/pull/158**.
- All errors are now tracked in a [single project](https://sentry.io/organizations/creative-commons/issues/?project=1525413). This makes it much easier to manage errors across environments:
- Using Sentry Environments for (development|staging|production) filtering
- Using an `SSR:true|false` tag to detect errors on server-side-rendered pages
- Connected Sentry GitHub app, which allows us to link GitHub issues to Sentry errors for easier debugging
- Added a GitHub Action for Sentry Releases, which will allow us to narrow down errors to the release in which they first appeared
- Add …

Sentry Error Reporting Improvements

---

src/components/FooterSection.vue
src/components/HeroSection.vue
src/components/NavSection.vue
src/locales/en.json
src/locales/fr.json
src/pages/FeedbackPage.vue

Related to #996  by @brenoferreira 
Internationalizes aria-labels from the homepage, header and footer
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated …
```

Internationalize aria-labels from the homepage

---

src/locales/en.json
src/locales/fr.json
src/pages/AboutPage.vue
src/pages/FeedbackPage.vue

Related to #996  by @brenoferreira 
Internationalize aria-labels for about page and feedback page
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the …
```

internationalize aria-labels for about page and feedback page

---

.eslintrc.js
package-lock.json
package.json
src/components/AppModal.vue
src/components/ContentReport/ContentReportForm.vue
src/components/ContentReport/DmcaNotice.vue
src/components/ContentReport/OtherIssueForm.vue
src/components/ContentReport/ReportError.vue
src/components/Filters/FilterBlock.vue
src/components/Filters/FilterChecklist.vue
src/components/Filters/FiltersList.vue
src/components/ImageDetails/CopyLicense.vue
src/components/ImageDetails/PhotoDetails.vue
src/components/ImageDetails/ReuseSurvey.vue
src/components/ImageDetails/SocialShareButtons.vue
src/components/LocaleSelector.vue
src/components/MetaSearch/MetaSearchCard.vue
src/components/NavSection.vue
src/components/PhotoTags.vue
src/components/SafeBrowsing.vue
src/components/ScrollButton.vue
src/components/SearchGridForm.vue
src/components/SearchGridManualLoad.vue
src/components/SearchRating.vue
src/components/Tooltip.vue
src/pages/FeedbackPage.vue

Related to #1000  by @brenoferreira 
Adds a11y plugin to the eslint config (https://www.npmjs.com/package/eslint-plugin-vue-a11y)
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

setup vue-a11y for eslint

---

.eslintrc.js
src/components/ImageDetails/PhotoDetails.vue
src/components/SafeBrowsing.vue
src/components/SearchGridForm.vue

Fixes #1052  by @zackkrida 
Fixes a double event trigger bug when opening a modal, and brings back invisible search bar in browse page.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```

modal accessibility

---

package-lock.json
package.json
src/components/HeroSection.vue
src/locales/en.json
src/locales/fr.json

Fixes #1124, #1125
Adds a subtitle to the homepage, which contextualizes cc search.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```

Update vocabulary + bulma, Add subtitle

---

src/locales/en.json

Fixes #1133 by @annatuma 
It changes license to license or public domain & sources to source
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the …
```

Made the appropriate changes to filters names

---

src/components/ImageDetails/ImageAttribution.vue
src/components/ImageDetails/ImageInfo.vue
src/components/MetaSearch/MetaSearchCard.vue
src/locales/en.json
test/unit/specs/components/ImageDetails/image-info.spec.js

Fixes #1135 by @annatuma 
Removes license plate for CC0 and PDM from information section and changed license to public domain
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```

removed license plate for cc0 and pdm 

---

src/components/ImageDetails/ImageInfo.vue

Fixes #1137 by @annatuma 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Show provider only if source and provider are different

---

package-lock.json
package.json

This will unblock #1069 and possibly other issues.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

Update vocabulary to v2020.08.4

---

src/components/HeroSection.vue
src/components/ImageDetails/PhotoDetails.vue
src/pages/AboutPage.vue
src/pages/SearchHelpPage.vue

Fixes #1069  by @zackkrida 
Added semantic heading tags and classes
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```

fix: Added '<h1>' tags and heading classes

---

src/components/ImageDetails/CopyLicense.vue

Fixes #1136 by @annatuma 
Changes Rich Text and Plain Text for CC0 and PDM under Creditor tools according to the issue.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Changed rich and plain text for CC0 and PDM

---

src/components/ImageDetails/PhotoDetails.vue

Fixes #1147  by @annatuma 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Initialized the ProviderName which was undefined initially 

---

src/components/Filters/LicenseExplanationTooltip.vue

Fixes #1132  by @zackkrida 
It fixes broken links of public domains in the License Tooltip
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```

Fix broken links in License Tooltip

---

src/components/Filters/FilterBlock.vue

Fixes #[issue number] by @[issue author]
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous …
```

Wrong-alignment of on-focus indicator for filter tabs #1142

---

package-lock.json
package.json
src/components/AppModal.vue
src/components/SafeBrowsing.vue

Fixes #1052  by @zackkrida 
Introduces trap focus in AppModal and SafeBrowsingModal
Uses [focus-trap-vue](https://github.com/posva/focus-trap-vue)
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```

add trap focus to modals

---

package-lock.json
src/components/FooterSection.vue

Fixes #1118  by @AyanChoudhary 
Before the changes, we have an h5 tag in the footer and this has been changed to <span> without affecting changes in 
frontend. 
It has some CSS properties as it has with h5 tag.
Check if there is span tag used in replacement of h5 tag  on line 150 on the location https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/FooterSection.vue 
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```

h5_replaced(fixes #1118)

---

src/components/SearchGridForm.vue
src/locales/en.json
test/unit/specs/components/search-grid-form.spec.js

Fixes ##1160 by @annatuma 
Adds dynamic placeholder values for 'Search' input
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Changed the placeholder values

---

package-lock.json
src/utils/getLegacySourceUrl.js

Added Vimeo to Video Meta Search as suggested. It now shows Vimeo too for search results. 
Fixes #1162   by @annatuma 
Previously, Link to results from Vimeo was not in the video meta search. Now it is!
As suggested by @annatuma Vimeo performs search query in the following format:
https://vimeo.com/search?license=(license_type)&q=(search_query)
Therefore, I added license and q parameters to legacySourceMap object in [https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/utils/getLegacySourceUrl.js](url)  as suggested by @zackkrida. 
One can perform any search item and then checkout in videos tab and find link to vimeo's search results filtered by CC BY license there. 
index.md`).
[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688 …

Added Vimeo to videos meta search #1162

---

src/components/NavSection.vue
src/locales/en.json
src/pages/AboutPage.vue
src/pages/FeedbackPage.vue
src/pages/SearchHelpPage.vue
src/pages/SourcePage.vue

Fixes #1179 by @annatuma 
Restructures the nav on cc search, also normalizes the the container size and heading of each page to use bulma's grid. Previously every page on the site had a different title size and position!
Compare the live site to these after shots:
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```

Standardize page layouts/headings and restructure nav

---

src/components/FooterSection.vue

Fixes #1184 by @zackkrida 
It removes duplicate cc contact info from footer
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Removed duplicate cc contact info from footer

---

src/pages/PhotoDetailPage.vue

Fixes #1189 by @annatuma 
Enables web monetization on single image result pages. I took care of this because while it was a simple edit, I think it would have been confusing for folks new to the project.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```

Enable web monetization on single result pages

---

package-lock.json
package.json
src/components/FooterSection.vue

Fixes #1190 by @zackkrida 
Added filled heart icon in donate button. 
There are changes in dependencies in `package.lock.json` 
All test passing. 
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```

Add filled heart icon in donate button

---

src/pages/SourcePage.vue

Fixes #1187  by @annatuma 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Fix Smithsonian Institute link

---

src/components/MetaSearch/MetaSearchCard.vue
src/utils/getLegacySourceUrl.js

Fix google meta search in response to [recent changes](https://www.forbes.com/sites/johanmoreno/2020/08/31/attribution-required-google-images-scraps-labeled-for-reuse/#7c4285f744bd). Now generates the following urls:
```
https://www.google.com/search?q=dogs&tbm=isch&tbs=il:cl
q = search term
tbm = search type (isch = image search)
tbs = license type (il:cl = creative commons)
```
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Fix google meta search

---

src/locales/en.json

#1205 by @annatuma 
Added "and tools" to the text under search bar.
Before
After Changes
- [x ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [x ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x ] My commit messages follow [best practices][best_practices].
- [x ] My code follows the established code style of the repository.
- [x ] I tried running the project locally and verified that there are no
<details>
```
Version 1.1
Suite D4700
San …
```

Fixed text under Search Bar on Homepage

---

src/components/NavSection.vue

Fixes #1203  by @zackkrida 
Changed position of Meta Search from 'About' to 'Resources'
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

changed position of meta search from 'about' to 'resources'

---

src/utils/attributionHtml.js

Fixes #1208 by @zackkrida 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Added image_id parameter to licence URL

---

src/locales/en.json
src/pages/SupportPage.vue

Fixes ##1218 by @zackkrida 
It fixes a typo as mentioned in the issue.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Changed the text to 'The search engine for the open movement'

---

src/components/HeaderSection.vue
src/pages/SupportPage.vue

Fixes the donation links in the support page and fixes the spacing below the banner, so it's not too close to page titles on content pages.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Fix support page donate links; Tweak banner spacing

---

package-lock.json
package.json
src/analytics/events.js
src/components/DonationBanner.vue
src/components/FooterSection.vue
src/pages/SupportPage.vue

Doing a quick patch release v2020.9.3, to add analytics to the donation banner and fix a small styling bug. I think it's worth the trouble!
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Release v2020.9.3

---

src/components/SearchGridForm.vue

Fixes #1227  by @adrijshikhar
Fixes alignment of search icon
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```

Fixes search icon alignment

---

src/components/SaferBrowsing.vue
src/components/SearchRating.vue

Fixes #1221 by @zackkrida 
It changes the color of yes/no and safer browsing link to tomato for accessibility reasons.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

Issue #1221 changed the color to tomato

---

.cc-metadata.yml

Since this repo will be entering maintenance mode and will no longer accept PR, it makes sense to unfeature this repo from the Project List page on the CC OS site.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the …
```

Unfeature repository as it is entering maintenance mode

---

README.md

Updates the project README with the following header:
> ## ⚠️ Notice: This project is on hold, and not under active development. We are not accepting new issues or pull requests. You can learn more at: [Upcoming Changes to the CC Open Source Community — Creative Commons Open Source](https://opensource.creativecommons.org/blog/entries/2020-12-07-upcoming-changes-to-community/).

Update README.md with discontinued status

---

package-lock.json
package.json
src/abTests/experiments/donationLanguage.js
src/abTests/index.js
src/store/index.js
src/utils/sixpack.js

This PR fixes the initialization of the a/b tests.
The object used to initialize a/b experiments was using an object to store a/b experiment cases in the store, but an array in the `sixpack` package. This PR converts cases object into an array, and adds a JSDoc type annotation to to prevent this kind of errors.
Additionally, the URL for the `sixpack` a/b participation had an extra slash, so the request did not receive a response.
The changes to sentry version number and `nuxtServerInit` were introduced because it was impossible to run the code without them.
The unit tests in `ab-tests.spec.js` pass, but throw `Error: Cross origin http://localhost forbidden` error.
index.md`).
<details> …

Fix a/b tests initialization

---

.cc-metadata.yml
.github/CODEOWNERS
README.md
package-lock.json
package.json
src/abTests/experiments/donationLanguage.js
src/abTests/index.js
src/store/index.js
src/utils/sixpack.js

Releases 2021.5.1 and fixes npm security bugs via `npm audit fix`
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```

Release 2021.5.1 and fix npm security bugs
