creativecommons/cccatalog-frontend

src/components/FooterSection.vue, src/components/HeaderSection.vue, src/components/NavSection.vue, src/components/SearchGrid.vue, src/components/ShareBar.vue, src/pages/ShareListPage.vue
Adding ability to add list item on mobile
- Modified code to make it easier to add images to lists on mobile. Changed image size to 44px based on Apple recommendation.
1.
-
-
=> Adding ability to add list item on mobile

src/store/share-list-store.js
Fix for share list images property being removed
=> Fix for share list images property being removed

src/pages/PhotoDetailPage.vue
This PR fixes the following issues:
-  fix for license url on photo detail page when license type is CC0 or PDM.
=> Fix for license url (CC0, PDM) on photo detail page

src/api/ImageProviderService.js, src/components/SearchGrid.vue, src/components/SearchGridFilter.vue, src/store/image-provider-store.js
This PR does the following: 
- Fixes issue with `Museums Victoria` provider, when filtering.
- Adds the ability to contain images, so they aren't cropped within the search grid.
- Fixes issues displaying error code, when retrieving provider stats.
=> Improvements for search grid

index.html, src/router/index.js
Google Analytics now updates the URL recorded and sends a new pageview when a user navigates within the single page app.
- Set up a separate Google Analytics ID for development/staging and used it conditionally so that Google Analytics can be tested locally.
- Updated URL sent to Google Analytics and logged a new pageview when the Vue Router navigates to a new route.
- Disabled linting of Google Analytics code.
Tested by visiting pages locally and made sure Google Analytics was showing the correct URL (e.g. `/photos/559a18bc-2e9d-4d7a-8a9c-ba522cb1498d` in the Real-Time stats.
List of pages from production Google Analytics data:
Page visit data when I was testing locally:
=> Fix Google Analytics not being configured for an SPA (#116)

README.md, build/webpack-dev-conf.js, config/index.js, test/e2e/specs/test.js
This PR updates the documentation and the webpack output with a notice about the application running on HTTPS instead of HTTP. This way, people new to the codebase won't be lost when they try to access it on http://localhost:8080/ and see nothing being served
=> Update setup documentation about HTTPS

src/router/index.js
Instead of sending only the relative URL to the `page` command of GA, this change sends the query string parameters as well. This allows the analytics to collect which terms are being searched for.
Example:
Before the URL sent to the `page` command was `/search`.
Now it sends `/search?q=landscapes`
=> Sends search params to GA page command

src/components/CopyButton.vue, src/pages/PhotoDetailPage.vue
Currently the "Copy to HTML" and "Copy to Text" buttons on the Photo detail pages ([example here](https://ccsearch.creativecommons.org/photos/2a5ff4cd-7be0-4fd7-bafd-dace875f1874)) offer no indication that text has actually been copied. 
This PR adds "Copied!" text to the copy buttons after the text is successfully copied:
Live Demo: https://dist-cwpsijvzyr.now.sh/ (visit any image detail page)
It also extracts the copy button logic from `PhotoDetailPage.vue`into a standalone component and [simplifies previous logic](https://github.com/creativecommons/cccatalog-frontend/blob/531e2583276bfd1e8064f2d7aec8155f60ac8975/src/pages/PhotoDetailPage.vue#L279) for adding _new_ "Copy" buttons in the future (relevant to: #106).
```vue
// Accepts a single prop for the text to be copied
// displays …
```
=> Add visual indication of success when using "Copy" buttons

src/components/SearchGridFilter.vue
Fixes #139 by adding the Cleveland Museum of Art and a few others that still hadn't been added to the filter list, but had their works already added to our database, according to http://api.creativecommons.engineering/statistics/image.
There's a provider with code `nhl` that I don't know the full name.
=> Adds new providers to search filters

src/api/ImageProviderService.js
Adds the new providers to the about page
- There's a provider with code `nhl` that I don't know the full name and URL.
=> Add new providers to about page

src/components/CopyButton.vue, src/components/PhotoDetails.vue
This fixes a bug on the details page that was caused by eager evaluation of these functions:
https://github.com/creativecommons/cccatalog-frontend/blob/master/src/components/PhotoDetails.vue#L105
and 
https://github.com/creativecommons/cccatalog-frontend/blob/master/src/components/PhotoDetails.vue#L116
This changes it to a lazy evaluation so that it's not called when the image hasn't finished loading.
=> Fix call to toUpperCase on undefined value on render

src/components/PhotoDetails.vue
Fixes #105 Removes the `<a>` HTML tag that was added to the text when the user clicked the "Copy to text" button on the image details page
The copied text now is, for example:
> "Released to Public: Hubble Looks at Monocerotis by NASA, ESA, and Hubble Heritage Team(NASA)" by pingnews.com is licensed under CC PDM 1.0. To view a copy of this license, visit: https://creativecommons.org/publicdomain/mark/1.0/
=> Remove HTML tag on  copy to text button click

src/pages/HomePage.vue
Fixes #156 so the label background doesn't become larger than the image.
=> Fix width of category label on home page

src/components/PhotoTags.vue, src/pages/PhotoDetailPage.vue
This fixes a few minor bugs in the image details page, including an undefined value that was causing some errors to be thrown and a bug that caused the a previous image to be still visible when visualizing another image (see GIFs below).
_bug reproduction: when you click to see the second image, you still see the first image rendered and then the new image is displayed.
_bug is fixed and the previous image isn't displayed before the second image is rendered_
=> Fix minor bugs on image details page

src/components/PhotoDetails.vue, test/unit/specs/components/photo-details.spec.js
Renders "CC0 1.0" instead of "CC CC0 1.0"
Fixes #194
=> Fix CC0 text on photo details page

src/utils/prepareSearchQueryParams.js, test/unit/specs/utils/prepareSearchQueryParams.spec.js
Removes leading and trailing whitespace from the "q" key of search params
Fixes #170
=> strip whitespace from queries

src/components/PhotoDetails.vue, src/utils/decodeData.js, test/unit/specs/utils/decodeData.spec.js
-> Decodes the data encoded in the API results on the front-end.
-> Renders "Léontine Walter" instead of "L\xe9ontine Walter". 
-> Problem Detected:- The characters in data returned by API are double escaped.
Fixes #192, #181, #154 and #107
=> Fix encoding on Photo Details page

src/components/FooterSection.vue
* There was a dead relative link to /about/contact, but no such page exists. The contact page is externally located at https://creativecommons.org/about/contact/
[Link to existing Issue #]
=> Fixed dead contact link

src/styles/photodetails.scss
In Safari, the photos end up being overflowed into the tags section. This helps prevent it.
Before:
After:
[Link to existing Issue #]
=> Photo overflowing into tags section on Safari

src/components/PhotoDetails.vue, test/unit/specs/components/photo-details.spec.js
CC search displays creators as anchor tags regardless of whether the `creator_url` attribute on `image` is populated or isn't. This PR corrects that by removing the anchor tag in case `creator_url` has a falsy value. This also updates the HTML attribution for such images, by avoiding HTML with `<a href="null">...</a>` situations.
This PR addresses issue #181 raised by @janeatcc.
The screenshot shows the updated appearance of the `PhotoDetails` component.
=> Add a check on creator URL and conditionally render anchor tags

.travis.yml, src/components/PhotoDetails.vue, test/unit/specs/store/search-store.spec.js, test/unit/specs/utils/decodeData.spec.js, test/unit/specs/utils/prepareSearchQueryParams.spec.js
Runs ES Lint during the CI build, so that PRs with lint issues will fail build and not be allowed to be merged
Fixes #240
=> Run lint during CI build

src/components/SearchGridCell.vue
This is a _very minor_ pull request that truncates long titles with ellipses and adds the full title in the tooltip. This does not fix any open issue on the repository but does address a real-world hiccup.
Before:
After:
=> Ellipsise overflowing titles and show the full title on hover

src/components/PhotoDetails.vue
Fixes a bug that displays the IMAGE DOWNLOAD header when the watermark feature flag is disabled
=> Hide download header if watermark flag is disabled

src/components/PhotoDetails.vue
Updates the tooltip text for the CC watermark checkboxes
Fixes #256
=> Update tooltip for CC watermark

src/api/ImageProviderService.js, src/components/SearchGridFilter.vue, test/unit/specs/store/search-store.spec.js, test/unit/specs/utils/getParameterByName.spec.js
This PR resolves issue #293 raised by @janeatcc regarding the removal of all occurrences of 500px from the codebase.
The provider has been removed from the filtering dropdown and from the About page as well. Also if the query parameter is passed as `?provider=500px`, this is the result:
<details>
<summary>
</summary>
<p>
(a) The contribution was created in whole or in part by me and I have the right to submit it …
=> Remove all occurrences of 500px in the codebase

.circleci/config.yml
_Per the decision in a previous engineering meeting_, this PR replaces the Travis configuration file with the CircleCI configuration file, addressing issue #283 opened by @kgodey.
The tests being run are kept as close to the original Travis configuration as possible, while using the `docker` engine running the same Node version as the `Dockerfile`. One important difference is that lint and unit tests are run in parallel unlike in Travis.
**All that remains is to import the project into CircleCI and integrate with GitHub, which I presume I do not have permission to do so I'll defer to @kgodey or @brenoferreira.**
This is how the tests look in the CircleCI interface.
<details>
<summary>
</summary>
<p>
Copyright (C) 2004, 2006 The Linux Foundation …
=> Replace Travis with CircleCI

src/components/SearchGridFilter.vue
Change the `filters` order as requested @ #296 
The new order: _(Left to right)_
- All License types _(Fixed @ #320 , but I don't know what's the best way to merge them together. So, I kept them separately - Please advise here!)_
- All Licenses
- All Providers
- Search by Creator
=> Change order of filters

src/api/ImageProviderService.js, src/components/SearchGridFilter.vue
Fixes #312 
Removes NYPL provider from filters list and about page
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work …
=> Remove NYPL from providers list

src/components/LegalDisclaimer.vue, src/pages/AboutPage.vue, src/pages/FeedbackPage.vue
Fixes #290 #340 #298 
Updates the text on about page, the legal disclaimer on the photo details page, and adds a link to the report a bug in the feedback page
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an …
=> Update legal texts

src/components/CopyButton.vue, src/components/HeaderSection.vue, src/components/ImageAttribution.vue, src/components/LegalDisclaimer.vue, src/components/PhotoDetails.vue, src/components/ReuseSurvey.vue, src/pages/PhotoDetailPage.vue, src/styles/photodetails.scss, src/utils/attributionHtml.js
Fixes #326 #339 #338 #339 #346 
* Adds the reuse survey link
* Fixes the Verify At Source text
* Changes the attribution/html embed copy button text
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate …
=> Reuse survey

src/pages/AboutPage.vue
Fixes #290 
A follow-up PR to fix the `typo/whitespace` after #344 
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work …
=> Fix typos/whitespace on 'AboutPage'

src/components/HeroSection.vue
Fixes #354 
This PR:
- Fix the `CC Logo` overlapping the text above (Small screens only)
- Add `padding` to the `CC Logo` to look properly (Small screens only)
- Adjust the `.old-search-link` top space (All screens)
Here's the UI Difference:
| Before | After |
| ------- | ----- |
| ![Before](https://user-images.githubusercontent.com/16986422/56939563-58c9ab00-6b09-11e9-9d99-65a82ffa6b2e.png) | ![After](https://user-images.githubusercontent.com/16986422/56939568-5bc49b80-6b09-11e9-800f-04eb398a889b.png) |
--- …
=> Fix 'logo' bug on small screens

src/components/ImageAttribution.vue
=> Doesn't copy license icons for rich text

src/utils/attributionHtml.js
Fixes #352 
Adds an explicit `display: inline-block` to license icons on HTML embed, so it takes precedence for any global `<img>` styles that can cause the icons to line up vertically instead of horizontally.
---
(b) The contribution is based upon previous work that, …
=> Explicit style for license icons on html embed

CONTRIBUTING.md
Added information about the public roadmap document to the contribution guidelines.
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to …
=> Added link to roadmap

src/components/HeroSection.vue, src/pages/HomePage.vue
Fixes #377 
As @janeatcc reported, we have a responsive problem with `landscape` mode because our `Media Query` is specified according to the `width` only, not the `height`.
Please note: This PR also fixes the `height` responsive problem with the homepage' `logo`.
Before:
When Scrolling:
After (Android):
When Scrolling (iPhone):
---
(a) The contribution was created in whole or in part by me and I have the right to …
=> Fix responsive issues on 'landscape' mode

src/components/SearchGridForm.vue
Fixes #377 
Stop overlapping the `Search inputs/filters` on small screens by overwriting the default `foundation` flex style rules.
Before:
After:
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate …
=> Fix 'search inputs/filters' overlapping on small screens

src/api/ImageProviderService.js, src/components/MasonrySearchGridCell.vue, test/unit/specs/components/masonry-search-grid-cell.spec.js
Fixes #368 
Fixes a bug on the rendering of the CAPL provider logo and applies a general fix for the search results if the same issue comes up in the future
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an …
=> Fixes CAPL provider logo

src/store/search-store.js, test/unit/specs/store/search-store.spec.js
=> Hides the search results in case the user is performing a new search

src/components/SearchGrid.vue
Fixes #328 
Disables the animations in the search results grid, based on user feedback
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license …
=> No animation in search results grid

src/components/ReuseSurvey.vue
Fixes #326 
Automatically fills the link to the image on the reuse survey
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that …
=> fills link to image in survey

src/components/HeroSection.vue, src/components/HomeLicenseFilter.vue, src/components/NavSection.vue, src/components/SearchGridFilter.vue, test/unit/specs/components/home-license-filter.spec.js
Fixes #297 
Adds the license type filters to the home page, allowing users to filter their search for commercial usage and modify/adapt
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source …
=> License type filters on home page

package.json
The old end to end tests were removed. This PR removes the NPM commands from the package.json file
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under …
=> Remove old end to end test commands

server.js
Changes the static asset `cache-control max-age` response header to 1 hour. It was 30 days, which is too long.
---
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the …
=> Change static asset cache duration

src/components/ImageSocialShare.vue, test/unit/specs/components/image-social-share.spec.js
Fixes #271 
This addresses the request in https://github.com/creativecommons/cccatalog-frontend/issues/271 for the image social sharing text to have the word "search" capitalized in the phrase `I found an image through CC Search @creativecommons: `. 
This does not address the part of the issue where sharing on Facebook does not bring up the image social sharing text. This is because the Facebook sharer doesn't look at inputs sent through. E.g. when we send:
`https://www.facebook.com/sharer/sharer.php?u=${shareURL}&t==${shareText}&href=${shareURL}`
It doesn't look at the `shareText` we're sending over. Facebook's sharer has changed to only look at the meta tags on the page. So to fix this issue we likely want  `<meta name="og:description"` to be dynamic and list the sharer text when …
=> Address Issue #271: Capitalize "search" in Social Share Text

src/pages/FeedbackPage.vue
Helps towards fixing #488 
Adds a `title` to the `iframe` for screen readers. Also changes the "Report a bug" `h1` to an `h2`, with the same styling, since a page should only have one `h1`.
#hacktoberfest
---
(b) The contribution is based upon previous work that, to …
=> Update Feedback Page

src/components/FooterSection.vue
Fixes #443
Result of adding "Contribute on GitHub" in footer:
New link is at lower right corner referencing [this](https://github.com/creativecommons/cccatalog-frontend) repo.
---
<details>
<summary>Developer Certificate of Origin Version 1.1</summary>
(b) The contribution is based upon previous work that, to …
=> Add link to Github repository

src/components/SearchGridManualLoad.vue, src/store/search-store.js
Fixes #526 
When there are no more images from the search to be loaded, it disables the button and also changes the text
(b) The contribution is based upon previous work that, to the best of my …
=> Makes 'Load More' button disabled if there are no more images

src/components/ImageAttribution.vue, src/components/ImageInfo.vue, src/components/LegalDisclaimer.vue, src/styles/photodetails.scss, test/unit/specs/components/image-info.spec.js, test/unit/specs/components/legal-disclaimer.spec.js
Fixes #409 
I've tried to answer the issue without breaking the existing layout of the section, applying just some small changes. I thought it would make sense to keep consistence between this element and the one in the Info tab, so I adapted the latter to reflect the changes.
I don't know if it's somehow acceptable, of course I'm available for adjustments, changes and further contributions. Feel free to ask!
This is the current result:
This is an alternate version I tried, but I thought the position wasn't quite right for a disclaimer:
---
Everyone is permitted to copy and distribute verbatim copies of this license …
=> Add logo verify at source

src/components/SearchGridManualLoad.vue
The CC Catalog API has a capped result count of 10,000 even when results exceed this amount. This fix is aimed at helping users understand this by reflecting it on the UI search results count whenever that is the case.
Screenshot showing updated change to search results count when >10K results
Screenshot showing original search result count when <10K results
---
(a) The contribution was created in whole or in part …
=> fixed count for image results >10K #540

src/components/SearchGridFilter.vue, src/components/SearchGridForm.vue
Fixes #575 
- As described in the issue, this PR adds a fixed filter sidebar as well as fixed searchbar up top while scrolling.
- This makes it easier to add filters and browse while they are scrolling
- Also it shows a more consistent view of the page, and doesn't leave whitespace there
**Screenshots**
*Initial*
*Scrolling*
*Hitting the bottom, with filters open*
**Methodology**
**Sidebar**
- Used the CSS property position as - `postion: sticky` to get this effect
- `position: sticky` has out of box support for all major browsers, without requiring any polyfills, as can be seen [here](https://caniuse.com/#feat=css-sticky)
- Also added `height: auto` since, when various filters are activated, they increase and decrease the filter sidebar height, so to contain that, height adjusted to auto …
=> Added CSS styles to fix issue-575

config/.env, src/api/ImageProviderService.js, src/api/ImageService.js, src/store/search-store.js, src/utils/searchQueryTransform.js, test/unit/specs/store/filter-store.spec.js, test/unit/specs/store/search-store.spec.js
Fixes #551 
**Changes made**
- Updated API calls from [v0](https://api.creativecommons.engineering/v0/) to [v1](https://api-dev.creativecommons.engineering/v1/)
- Made changes to the different query parameter names, example - provider to sources
- All of the changes have been made either in the `utils/searchQueryTransform.js` or the `store/search-store.js` actions, without affecting the state and props being used by the vue project
**Pending**
- Cannot find endpoint for POST request to `/analytics` in v0 or v1 of the API, but it is being used at `api/UsageDataService.js`
- Response for majority of the API calls are same, have not adjusted for minor tweaks or extra information received like- `attribution` is received in v1, whereas `metadata` is not received, but changes for them haven't …
=> Update code to confirm to API v1

src/components/LicenseIcons.vue
Fixes #772 
(b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by …
=> Fixed excessive spacing between license icons.

test/unit/specs/components/loading-icon.spec.js
Fix as a part of test coverage improvement for components (#232)
Related to #232  by @brenoferreira 
Added unit test for LoadingIcon component.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Added unit test for LoadingIcon component

test/unit/specs/components/filter-checklist.spec.js
Related to #232 by @brenoferreira 
Added unit tests for FilterChecklist component (100% coverage)
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> #232 - Added unit tests for FilterChecklist component

src/components/HeroSection.vue, src/components/SearchGridForm.vue
Fixes #793 by @panchovm 
Uses Bulma's Form addons to fix the styling issue https://bulma.io/documentation/form/general/#form-addons
<details>
```
Version 1.1
Suite D4700
of …
```
=> Fix search form layout

src/components/HeroSection.vue, src/components/NavSection.vue
Fixes #856  by @Abbas-000
On a new design we moved the search guide to the navbar, so that addresses the issue of overlapping links.
<details>
```
Version 1.1
Suite D4700
of …
```
=> Moved search guide link to navbar

src/components/ContentReport/DmcaNotice.vue
Quick fix to a broken back button 
_broken_
_fixed_
<details>
```
Version 1.1
Suite D4700
license and I have the …
```
=> Fix back button on dmca notice

src/components/SearchGridFilter.vue
Reverts creativecommons/cccatalog-frontend#903
This introduced a bug on mobile because of the `height` style.
=> Revert "Added Scroll bar to filters for desktop users"

src/components/ImageDetails/ImageAttribution.vue
Fixes a bug on the rich text attribution copy that was being caused by an element with a duplicated `id` attribute
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove duplicated id which breaks rich text attribution copy

package.json
Fixes #985 by @localjo
Removes `"type": "module"` from `package.json`, which enables the application to build and run on versions of node > 10.x.
This field was unused by any of the existing configuration, so it should be a consequence-free move to remove it.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```
=> Fix ability to run on newer node versions (Fixes #985)

src/components/RelatedImages.vue
Fixes #960 
Removes extra spacing on related images (without altering the main search results' view).
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> Fix related image spacing

src/components/Filters/FiltersList.vue
Partially Fixes #1050  
<details>
```
Version 1.1
Suite D4700
license and I have the right under that license to …
```
=> showing 'Use' when audio or video is open

package-lock.json, package.json, src/components/CollectionItem.vue, src/components/MetaSearch/MetaSourceList.vue, src/components/NavSection.vue, src/components/SearchGridCell.vue, test/unit/specs/components/collection-item.spec.js
Some small pre-release cleanup to routing:
- Version bump `vue-router`
- Switch internal links to be `<router-link>`s instead of `<a>` tags (the preferred approach by vue)
This will likely fix some sentry errors outlined in #1042.
Also removed a stray `console.log` from a previous commit.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```
=> Update vue router and fix internal links to be `<router-link>`s

src/components/AppModal.vue, src/components/MetaSearch/MetaSearchForm.vue, src/components/MetaSearch/MetaSearchModal.vue
Fixes #1082 by @kgodey (@annatuma)
Adds a disclaimer for application of the 'use' filters to meta search.
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered …
```
=> Add label for use filters

src/components/SearchGridCell.vue
Fixes #1084 by @zackkrida 
Fixes how img width/height is calculated to fix the existing masonry-style flexbox layout.
> before
> after
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix img width/height detection

src/components/CollectionItem.vue
Fixes #1035 by @annatuma 
Retrieves the collection images from the api instead of our hardcoded list of images. I am currently falling back to our manually-generated list because the dev site and local development use the dev version of the api:
`https://api-dev.creativecommons.engineering/v1/sources?format=json&limit=500`
which doesn't have all of the images uploaded (they _are_ on the main api though).
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Use source logos from api

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Adds the 'release drafter' GitHub action which will automatically write release notes every time a pull request is merged into the primary branch of the repo. The test of this action I ran can be viewed here: https://github.com/zackkrida/test-release-note-generator/releases 
<details>
```
Version 1.1
Suite D4700
have the …
```
=> Implement release drafter

src/components/MetaSearch/MetaSearchCard.vue, src/utils/getLegacySourceUrl.js
Adds https://nappy.co to meta image search.
<details>
```
Version 1.1
Suite D4700
of my …
```
=> Add Nappy.co to meta image search

src/components/AppModal.vue
Fixes a bug introduced by new modal changes that breaks SSR on the 'browse' page.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```
=> Fix modal ssr breaking bug

src/components/NavSection.vue
Switches cc search to the 'large' header variation of Vocabulary.
The 'small' version in use was inaccurate anyway, and was more of a 'medium' version. This PR switches to the large which only adds ~10px of spacing, making the global header button look much nicer.
<details>
```
Version 1.1
Suite D4700 …
```
=> Switch to large header

src/router/redirectTo.js, test/unit/specs/router/redirectTo.spec.js
Related to #1042 by @zackkrida 
Stops the throwing of `NavigationDuplicated` errors, as these are valid in our app and don't pose a problem. 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Swallow duplicate nav errors

src/components/CollectionItem.vue
Fixes displaying source logos from S3, was broken due to some bad/old conditional logic I overlooked.
Also adds styles for img fallback text when images aren't present.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix faulty conditional that prevented source logos from loading

src/router/index.js
These redirects will be configured server-side in our nginx configuration, but it doesn't hurt to have some redundancy and do this client-side as well.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
=> Client-side redirection from `/collections/:name` to `/search?source=:name`

src/App.vue
Fixes the global header tab to always be aligned with the site menu, and makes sure it only renders once.
> before
> after
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
=> Make sure global header renders once; Remove max-width restriction on global header tab

package-lock.json, package.json, src/utils/getProviderName.js
If a source or provider name isn't in the providers api route, we will fallback to formatting the 'ugly' provider slug from the api.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Source and Provider name fallback

src/components/Filters/FilterBlock.vue, src/components/Filters/FilterChecklist.vue
Related to #1106  by @zackkrida 
Fixes the issue where the license explanation tooltip and the close button on filter tags were not listening to an *enter* keypress.
Added the ```v-on:keyup.enter``` attribute to enable listeners for an *enter* keypress
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, …
```
=> Add keypress listener to tooltip img and filter close button

src/store/filter-store.js, src/utils/local.js
Fixes #506 by @annatuma 
Stores the open/close state of the filter sidebar in localstorage for desktop users. This means on repeat visits to the `/search` page the user's previous sidebar state will be respected.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
=> Store filter sidebar toggle state in localstorage

.github/CODEOWNERS, .prettierignore, CODEOWNERS, package.json
Fixes issues with duplicate codeowners files and moves to more standard location. Updated prettier config because it was trying to format the new codeowners file.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the …
```
=> Fix codeowners files

src/components/ImageDetails/CopyLicense.vue
Fixes #1155 by @zackkrida
> Anything marked with **CC0** or **PDM** has two typos in the "Plain text" attribution tab:
> 1. Says "licensed" instead of "marked"
> 2. Says "to the terms" instead of "to view the terms"
Now, the fix resolves these issues as you can see in following screenshot:
index.md`).
<details>
```
Version 1.1
Suite D4700
By …
```
=> Fixed plain text attribution typos for tools

src/components/ContentReport/ContentReportForm.vue, src/components/ContentReport/DmcaNotice.vue, src/components/ContentReport/OtherIssueForm.vue, src/components/ImageDetails/PhotoDetails.vue, test/unit/specs/components/ContentReport/content-report-form.spec.js
Fixes https://github.com/creativecommons/vocabulary/issues/411 on vocabulary and other issues.
This PR makes some improvements to the content reporting form:
- Removes an extra '.' at the end of the DMCA notice sentence
- Fixes extra spacing between DMCA notice paragraphs
- Fixes 'next' button disabled color
- Shows formatted provider name in DMCA form instead of slug
- Fixes line height of info paragraph
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
=> Content Reporting Form cleanup

src/components/SearchGridForm.vue, src/store/search-store.js, test/unit/specs/store/search-store.spec.js
Fixes #1161 by @annatuma 
- Removes redirect to image results when clicking "search" button on audio|video tabs
- "Live" updates meta search buttons when the user types in the search input on audio|video tabs
- Note this functionality was already working for meta image search
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Fix meta search query update issues

src/store/search-store.js
Fixes a devsite bug where the homepage search input doesn't actually submit. As this is fairly critical and affects folks' ability to test on the devsite, I'll push this and get a retroactive code review.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```
=> Fix failed redirection on homepage search input

src/components/SaferBrowsing.vue, src/components/SearchGridManualLoad.vue, src/locales/en.json, src/locales/fr.json
Fixes #1185 by @TimidRobot 
Replaces "safe browsing" with the more accurate "safer browsing" in the front end. 
Also renames components and labels internally in the repo with this revised language.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
=> Safer browsing language update

src/pages/MetaSearchPage.vue
Fixes broken images on the meta search page. Image paths were only working locally.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```
=> Fix asset paths on Meta Search Page

.github/workflows/project-automation.yml
Replacement for #1210 that targets develop instead of master.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> Replace `ORG_GITHUB_TOKEN` with `ADMIN_GITHUB_TOKEN`

src/analytics/events.js, src/components/DonationBanner.vue, src/components/FooterSection.vue, src/pages/SupportPage.vue
This PR fixes a spacing bug with the 'Not today' button on the donation banner. It also adds Google analytics events for:
- Clicks of donation links on the site
- Dismissal of the donation banner (can give us a sense of how "annoying" people find this)
Goals have been created for these events:
The "Donation Link Click" goal can be further filtered by the event 'label' in google analytics, which will be one of the following values:
- `banner` The click was the donate button inside the donate header banner
- `footer` The click was from the donate button in the site's footer
- `support-page` The click was one of the many buttons on the support page
In general, this isn't a perfect implementation code-wise, and should be improved in a bigger refactor of how analytics is set up in the app. I …
=> Support analytics and style cleanup

src/components/ImageDetails/CopyLicense.vue, src/components/ImageDetails/ImageInfo.vue, src/components/ImageDetails/PhotoDetails.vue
Fixes #1237 by @aldenstpage 
Currently we track when users click on big green "Go to image's website" button  and are redirected to an external URL.
However, the same link to an external URL of the image source exists in two other places: in the Rich text attribution box and in the Information Tab. There is also a link to creator profile below the image title and in the Rich text attribution box. I added action to send image id to the Analytics API when users click on any of these links.
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
=> Register Creator and Image source clicks with Analitics API
